version: '3.8'

services:
  frontend:
    build:
      context: ./idp_frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - idp-network

  backend:
    build:
      context: ./idp_backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
    networks:
      - idp-network
    restart: on-failure

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - idp-network

networks:
  idp-network:
    driver: bridge

volumes:
  postgres_data: